Projet .Net/Projet .Net/GestionAvocats/GestionAvocats/GA.UI.Web/Models/ErrorViewModel.cs
namespace GA.UI.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Projet .Net/Projet .Net/GestionAvocats/GestionAvocats/GA.UI.Web/Controllers/AvocatController.cs
using GA.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Controllers
{
    public class AvocatController : Controller
    {
        private readonly IAvocatService avocatService;

        public AvocatController(IAvocatService avocatService)
        {
            this.avocatService = avocatService;

        }
        // GET: AvocatController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AvocatController/Details/5
        public ActionResult Details(int id)
        {
            return View(avocatService.GetById(id));
        }

        // GET: AvocatController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AvocatController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AvocatController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AvocatController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AvocatController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AvocatController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Projet .Net/Projet .Net/GestionAvocats/GestionAvocats/GA.UI.Web/Controllers/DossierController.cs
using GA.ApplicationCore.Domain;
using GA.ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Controllers
{
    public class DossierController : Controller
    {
        private readonly IDossierService dossierService;
        private readonly IAvocatService avocatService;
        private readonly IClientService clientService;

        public DossierController(IDossierService dossierService,IAvocatService avocatService,IClientService clientService)
        {
            this.dossierService = dossierService;
            this.clientService = clientService;
            this.avocatService = avocatService;

        }

        // GET: DossierController
        public ActionResult Index()
        {
            return View(dossierService.GetMany().ToList());
        }
        [HttpPost]
        public ActionResult Index(string nom)
        {
            if(!string.IsNullOrEmpty(nom))
                return View(dossierService.GetMany().ToList().Where(d=>d.Avocat.Nom.Equals(nom)));
            else
                return View(dossierService.GetMany().ToList());
        }

        // GET: DossierController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DossierController/Create
        public ActionResult Create()
        {
            var clients = clientService.GetMany().Select(a => new { a.CIN, a.NomPrenom });
            var avocat = avocatService.GetMany().Select(a=>new{a.AvocatId, a.NomPrenom });
            ViewBag.ClientFK=new SelectList(clients, "CIN", "NomPrenom");
            ViewBag.AvocatFK=new SelectList(avocat, "AvocatId", "NomPrenom");
            return View();
        }

        // POST: DossierController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Dossier collection)
        {
            try
            {
                dossierService.Add(collection);
                dossierService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DossierController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DossierController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DossierController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DossierController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Projet .Net/Projet .Net/GestionAvocats/GestionAvocats/GA.UI.Web/Controllers/HomeController.cs
using GA.UI.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GA.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Projet .Net/Projet .Net/GestionAvocats/GestionAvocats/GA.UI.Web/Views/Avocat/Details.cshtml
@model GA.ApplicationCore.Domain.Avocat

@{
    ViewData["Title"] = "Details";
}


<div>
    <h4>Avocat</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEmbauche)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEmbauche)
        </dd>
    </dl>
</div>

Projet .Net/Projet .Net/GestionAvocats/GestionAvocats/GA.UI.Web/Views/Dossier/Create.cshtml
@model GA.ApplicationCore.Domain.Dossier

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Dossier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateDepot" class="control-label"></label>
                <input asp-for="DateDepot" class="form-control" />
                <span asp-validation-for="DateDepot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientFK" class="control-label"></label>
                <select asp-for="ClientFK" class ="form-control" asp-items="ViewBag.ClientFK"></select>
            </div>
            <div class="form-group">
                <label asp-for="AvocatFK" class="control-label"></label>
                <select asp-for="AvocatFK" class ="form-control" asp-items="ViewBag.AvocatFK"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Cols" /> @Html.DisplayNameFor(model => model.Cols)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Frais" class="control-label"></label>
                <input asp-for="Frais" class="form-control" />
                <span asp-validation-for="Frais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Projet .Net/Projet .Net/GestionAvocats/GestionAvocats/GA.UI.Web/Views/Dossier/Index.cshtml
@model IEnumerable<GA.ApplicationCore.Domain.Dossier>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des Dossiers</h1>

<form asp-action="Index">
    <label for="nom">Avocat</label>
    <input type="text" name="nom"/>
    <input type="submit" value="Search" />
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cols)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Frais)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cols)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Frais)
            </td>
            <td>
               <a asp-action="Details" asp-controller="Avocat" asp-route-id="@item.Avocat.AvocatId">Avocat</a> |              
            </td>
        </tr>
}
    </tbody>
</table>

Projet .Net/Projet .Net/GestionAvocats/GestionAvocats/GA.UI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>